# Полная настройка PostgreSQL для CRM: БД, пользователь, миграция, .env
#
# Вариант A — файл с паролем (удобно для Cursor):
#   1. copy .env.postgres.local.example .env.postgres.local
#   2. Впишите POSTGRES_ADMIN_PASSWORD=...
#   3. powershell -ExecutionPolicy Bypass -File scripts\complete_postgres_setup.ps1
#
# Вариант B — пароль в командной строке:
#   powershell -ExecutionPolicy Bypass -File scripts\complete_postgres_setup.ps1 -AdminPassword "пароль"

param(
    [string]$AdminPassword = "",
    [string]$CrmDbPassword = "",
    [switch]$SkipMigrate
)

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $PSScriptRoot
Set-Location $Root

function Read-DotEnvFile([string]$Path) {
    $vars = @{}
    if (-not (Test-Path $Path)) { return $vars }
    Get-Content $Path -Encoding UTF8 | ForEach-Object {
        $line = $_.Trim()
        if (-not $line -or $line.StartsWith("#")) { return }
        if ($line -match "^([^=]+)=(.*)$") {
            $vars[$Matches[1].Trim()] = $Matches[2].Trim()
        }
    }
    return $vars
}

$localEnv = Read-DotEnvFile (Join-Path $Root ".env.postgres.local")
if (-not $AdminPassword -and $localEnv["POSTGRES_ADMIN_PASSWORD"]) {
    $AdminPassword = $localEnv["POSTGRES_ADMIN_PASSWORD"]
}
if (-not $AdminPassword) {
  $sec = Read-Host "postgres password" -AsSecureString
  $AdminPassword = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
      [Runtime.InteropServices.Marshal]::SecureStringToBSTR($sec)
  )
}

if (-not $CrmDbPassword) {
    if ($localEnv["CRM_DB_PASSWORD"]) {
        $CrmDbPassword = $localEnv["CRM_DB_PASSWORD"]
    } else {
        $CrmDbPassword = -join ((48..57) + (65..90) + (97..122) | Get-Random -Count 24 | ForEach-Object { [char]$_ })
    }
}

$psql = Get-ChildItem "C:\Program Files\PostgreSQL\*\bin\psql.exe" -ErrorAction SilentlyContinue |
    Sort-Object { [version]($_.Directory.Parent.Name -replace '[^\d.]','') } -Descending |
    Select-Object -First 1 -ExpandProperty FullName
if (-not $psql) {
    Write-Host "psql.exe not found. Install PostgreSQL." -ForegroundColor Red
    exit 1
}

$env:PGPASSWORD = $AdminPassword
$safeCrmPass = $CrmDbPassword -replace "'", "''"
$roleExists = (& $psql -U postgres -h localhost -d postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='crm'" 2>&1).ToString().Trim()
if ($roleExists -eq "1") {
    & $psql -U postgres -h localhost -d postgres -v ON_ERROR_STOP=1 -c "ALTER ROLE crm WITH PASSWORD '$safeCrmPass'" 2>&1 | Out-Host
} else {
    & $psql -U postgres -h localhost -d postgres -v ON_ERROR_STOP=1 -c "CREATE ROLE crm WITH LOGIN PASSWORD '$safeCrmPass'" 2>&1 | Out-Host
}
$dbExists = & $psql -U postgres -h localhost -d postgres -tAc "SELECT 1 FROM pg_database WHERE datname='crm'" 2>&1
if ($dbExists -notmatch "1") {
    & $psql -U postgres -h localhost -d postgres -v ON_ERROR_STOP=1 -c "CREATE DATABASE crm OWNER crm ENCODING 'UTF8'" 2>&1 | Out-Host
} else {
    Write-Host "Database crm already exists." -ForegroundColor Yellow
}

$encodedPass = [uri]::EscapeDataString($CrmDbPassword)
$pgUrl = "postgresql+psycopg2://crm:${encodedPass}@localhost:5432/crm"
$env:POSTGRES_URL = $pgUrl

pip install psycopg2-binary -q 2>$null

if (-not $SkipMigrate) {
    $dbPath = Join-Path $Root "instance\crm.db"
    if (-not (Test-Path $dbPath)) {
        $dbPath = Join-Path $Root "crm.db"
    }
    if (-not (Test-Path $dbPath)) {
        Write-Host "SQLite not found. Skip data copy." -ForegroundColor Yellow
    } else {
        $env:SQLITE_URL = "sqlite:///$($dbPath.Replace('\', '/'))"
        Write-Host "Migrating from $dbPath ..." -ForegroundColor Cyan
        python scripts/bootstrap_postgres.py
        if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
        python scripts/migrate_sqlite_to_postgres.py
        if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
    }
}

# .env
$envFile = Join-Path $Root ".env"
if (Test-Path $envFile) {
    $lines = Get-Content $envFile -Encoding UTF8
    $found = $false
    $newLines = foreach ($line in $lines) {
        if ($line -match '^\s*DATABASE_URL\s*=') {
            $found = $true
            "DATABASE_URL=$pgUrl"
        } else { $line }
    }
    if (-not $found) { $newLines += "DATABASE_URL=$pgUrl" }
    Set-Content -Path $envFile -Value $newLines -Encoding UTF8
}

$localOut = @(
    "# generated by complete_postgres_setup.ps1",
    "POSTGRES_ADMIN_PASSWORD=$AdminPassword",
    "CRM_DB_PASSWORD=$CrmDbPassword",
    "DATABASE_URL=$pgUrl"
)
Set-Content -Path (Join-Path $Root ".env.postgres.local") -Value $localOut -Encoding UTF8

Write-Host ""
Write-Host "Done." -ForegroundColor Green
Write-Host "DB user: crm (password in .env.postgres.local CRM_DB_PASSWORD)"
Write-Host "DATABASE_URL updated in .env"
Write-Host "Run: python scripts/verify_postgres.py"
Write-Host "Restart CRM."
