#!/usr/bin/env python3
"""Non-interactive PostgreSQL setup + SQLite migration (reads .env.postgres.local)."""

from __future__ import annotations

import os
import secrets
import subprocess
import sys
from pathlib import Path
from urllib.parse import quote_plus

ROOT = Path(__file__).resolve().parents[1]


def _load_postgres_local() -> dict[str, str]:
    p = ROOT / ".env.postgres.local"
    if not p.is_file():
        print("Create .env.postgres.local with POSTGRES_ADMIN_PASSWORD=...", file=sys.stderr)
        sys.exit(1)
    out: dict[str, str] = {}
    raw = p.read_text(encoding="utf-8-sig").strip()
    if not raw:
        print(".env.postgres.local is empty — save the file in the editor (Ctrl+S)", file=sys.stderr)
        sys.exit(1)
    for line in raw.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            out["POSTGRES_ADMIN_PASSWORD"] = line
            continue
        k, v = line.split("=", 1)
        out[k.strip()] = v.strip()
    if not out.get("POSTGRES_ADMIN_PASSWORD"):
        print("POSTGRES_ADMIN_PASSWORD missing in .env.postgres.local", file=sys.stderr)
        sys.exit(1)
    return out


def _ensure_role_and_db(admin_password: str, crm_password: str) -> None:
    import psycopg2
    from psycopg2.extensions import ISOLATION_LEVEL_AUTOCOMMIT

    conn = psycopg2.connect(
        host="localhost",
        user="postgres",
        password=admin_password,
        dbname="postgres",
        connect_timeout=10,
    )
    conn.set_isolation_level(ISOLATION_LEVEL_AUTOCOMMIT)
    cur = conn.cursor()
    cur.execute("SELECT 1 FROM pg_roles WHERE rolname = %s", ("crm",))
    if cur.fetchone():
        cur.execute("ALTER ROLE crm WITH LOGIN PASSWORD %s", (crm_password,))
        print("role crm: password updated")
    else:
        cur.execute("CREATE ROLE crm WITH LOGIN PASSWORD %s", (crm_password,))
        print("role crm: created")

    cur.execute("SELECT 1 FROM pg_database WHERE datname = %s", ("crm",))
    if cur.fetchone():
        print("database crm: already exists")
    else:
        cur.execute("CREATE DATABASE crm OWNER crm ENCODING 'UTF8'")
        print("database crm: created")
    cur.close()
    conn.close()


def _update_env(pg_url: str, admin_password: str, crm_password: str) -> None:
    env_path = ROOT / ".env"
    lines: list[str] = []
    if env_path.is_file():
        lines = env_path.read_text(encoding="utf-8").splitlines()
    found = False
    new_lines: list[str] = []
    for line in lines:
        if line.strip().startswith("DATABASE_URL="):
            new_lines.append(f"DATABASE_URL={pg_url}")
            found = True
        else:
            new_lines.append(line)
    if not found:
        new_lines.append(f"DATABASE_URL={pg_url}")
    env_path.write_text("\n".join(new_lines) + "\n", encoding="utf-8")

    local_path = ROOT / ".env.postgres.local"
    local_path.write_text(
        "\n".join(
            [
                "# generated by run_postgres_setup.py",
                f"POSTGRES_ADMIN_PASSWORD={admin_password}",
                f"CRM_DB_PASSWORD={crm_password}",
                f"DATABASE_URL={pg_url}",
                "",
            ]
        ),
        encoding="utf-8",
    )


def main() -> None:
    local = _load_postgres_local()
    admin = local["POSTGRES_ADMIN_PASSWORD"]
    crm_pass = local.get("CRM_DB_PASSWORD") or secrets.token_urlsafe(18)

    print("1/4 PostgreSQL: role + database...")
    _ensure_role_and_db(admin, crm_pass)

    pg_url = (
        f"postgresql+psycopg2://crm:{quote_plus(crm_pass)}@localhost:5432/crm"
    )
    os.environ["POSTGRES_URL"] = pg_url
    os.environ["DATABASE_URL"] = pg_url

    sqlite_path = ROOT / "instance" / "crm.db"
    if not sqlite_path.is_file():
        sqlite_path = ROOT / "crm.db"
    if sqlite_path.is_file():
        os.environ["SQLITE_URL"] = "sqlite:///" + sqlite_path.as_posix()
        print("2/4 bootstrap tables...")
        r = subprocess.run([sys.executable, "scripts/bootstrap_postgres.py"], cwd=ROOT)
        if r.returncode != 0:
            sys.exit(r.returncode)
        print("3/4 copy data from SQLite...")
        r = subprocess.run([sys.executable, "scripts/migrate_sqlite_to_postgres.py"], cwd=ROOT)
        if r.returncode != 0:
            sys.exit(r.returncode)
    else:
        print("2-3/4 no SQLite file, skip data copy")
        subprocess.run([sys.executable, "scripts/bootstrap_postgres.py"], cwd=ROOT, check=True)

    print("4/4 update .env...")
    _update_env(pg_url, admin, crm_pass)

    print("5/5 verify...")
    r = subprocess.run([sys.executable, "scripts/verify_postgres.py"], cwd=ROOT)
    if r.returncode != 0:
        sys.exit(r.returncode)
    print("OK. Restart CRM (start_public_test.ps1).")


if __name__ == "__main__":
    main()
